// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD94eIciXrwtMHT5PJ20TfrBrE6Dm291rY',
    appId: '1:1037891053876:web:81c2e3621b353288261d61',
    messagingSenderId: '1037891053876',
    projectId: 'ehop-backend',
    authDomain: 'ehop-backend.firebaseapp.com',
    storageBucket: 'ehop-backend.firebasestorage.app',
    measurementId: 'G-34F13PTVEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzh0bNOuazf3_Ql77uqVfX9sQQG9Fox3s',
    appId: '1:1037891053876:android:26618a34dc7e3ef3261d61',
    messagingSenderId: '1037891053876',
    projectId: 'ehop-backend',
    storageBucket: 'ehop-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAreoGvA_V1wIEzuk-buXqTT0jB3d1eqsM',
    appId: '1:1037891053876:ios:d392f0350b96967c261d61',
    messagingSenderId: '1037891053876',
    projectId: 'ehop-backend',
    storageBucket: 'ehop-backend.firebasestorage.app',
    iosBundleId: 'com.example.ehopPartner',
  );
}
